services:
  flask:
    build: ./app
    expose:
      - "43440"
    volumes:
      - model_volume:/app/models
      - /tmp:/tmp
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  model_volume:
