services:
  
  flask:
    build: .
    env_file: .env
    expose:
      - "5000"
    volumes:
      - model_volume:/app/models
    depends_on:
      - redis
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://default:redis@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://default:redis@redis:6379/0
    networks:
      - esg-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - esg-network

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    # seul le serveur web est exposé
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      # nécessaires pour la gestion des certificats
      - caddy_data:/data
      - caddy_config:/caddy_config

    depends_on:
      - flask
    networks:
      - esg-network

# permet au conteneurs de partager le même réseau
networks:
  esg-network:
    driver: bridge

volumes:
  model_volume:
  caddy_data:
  caddy_config:
