version: '3'

tasks:
  flask: flask --app flask_app.app run --reload --debug
  gunicorn: gunicorn --bind localhost:44444 flask_app.app:app 
  format: ruff format 
  lint: ruff check 
  fix: ruff check --fix
  celery: celery -A flask_app.tasks worker --loglevel=info --pool=threads
  dev: honcho start --procfile Procfile.dev
  token: python -m helpers.token  
